### ISSUE TITLE
[Bug]: pulumi-fly@0.1.13 has been compiled using terraform-provider-fly@0.1.11

### ISSUE THREAD

**Issue by kieranbrown** [dirien/pulumi-fly#224]
I may be incorrect, but I think the latest pulumi-fly version was compiled using terraform-provider-fly@0.1.11 instead of 0.1.13.

I'm getting a little confused testing out the latest 0.1.13 release locally. The Terraform provider recently fixed an issue with deleting IP addresses, upgrading this package to 0.1.13 doesn't seem to fix that issue. I'm not crazy proficient in golang but I found this line which may suggest 0.1.13 was compiled against 0.1.11? https://github.com/dirien/pulumi-fly/blob/f49c0db8d3691204216f26fb3078e4d64cb3d0de/provider/go.mod#L8

## Steps to replicate

```typescript
const app = new fly.App('app', {
  name: 'pulumi-fly-issue224-replication'
  org: 'personal',
  assignSharedIpAddress: false,
});

const ipv4 = new fly.Ip('ipv4', {
  app: app.name,
  type: 'v4',
  region: 'global',
});
```

Run a stack `up`,  then a stack `destroy` and it will error with this issue https://github.com/andrewbaxter/terraform-provider-fly/issues/3, this was resolved in https://github.com/andrewbaxter/terraform-provider-fly/releases/tag/v0.1.13

**Comment by ryanharmancl** [comment]
+1

**Comment by dirien** [comment]
@kieranbrown thanks for reporting, I tested it (also in TF) and it does not work with the version 0.1.13

```bash
➜ pulumi destroy -y -f
Destroying (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/dirien/fly-ts/dev/updates/15

     Type                 Name        Status                  Info
     pulumi:pulumi:Stack  fly-ts-dev  **failed**              1 error
 -   └─ fly:index:Ip      fly-ts-ip   **deleting failed**     1 error

Diagnostics:
  fly:index:Ip (fly-ts-ip):
    error: Error deleting ip address (app [my-dirien-app], ip []): Upstream graphql error: presence of either ipAddressId or ip is required
    Graphql path: releaseIpAddress

  pulumi:pulumi:Stack (fly-ts-dev):
    error: update failed

```

**Comment by dirien** [comment]
@kieranbrown this should work now! Please run:

```shell
pulumi plugin rm resource fly 0.1.13
```

To download the latest binary.

Do not forget to update your state file, if the resource was created with an older version. See https://github.com/andrewbaxter/terraform-provider-fly/issues/3#issuecomment-2165555755 for more details

**Comment by kieranbrown** [comment]
@dirien thanks for resolving! I'll test this out this evening and report back if I have any issues.
